jwt:
  secretKey: asdfkasdf89as7dfasd9fyuakjshdfa87sdf8iasuhfjas9d8f7as8idfuhjasd89f7asdi8fu

spring:
  #api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: ${ORDER_SERVICE_URI:lb://ORDER-SERVICE}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrdersFilter
            - name: Authorization
              args:
                isEnabled: false

        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URIlb://INVENTORY-SERVICE}
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Anuj
            - name: Authentication
