#eureka config
eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka
eureka.client.instance.prefer-ip-address: true

# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"

#zipkin
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
